.pre-commit-config.yaml

This fixes #31, I'm a bit confused why I had to do this but appears to be the reason why it was failing before https://github.com/brainglobe/cellfinder-core/runs/5305547649?check_suite_focus=true

Add `types-setuptools` as a `mypy` dependency

---

tox.ini

Even though https://github.com/brainglobe/cellfinder-core/pull/43 technically added support for 3.10, no tests were running on GH actions because I forgot to add Python 3.10 to the tox configuration. This fixes that.

Add Python 3.10 to tox environment list

---

CHANGELOG.md
src/cellfinder_core/detect/detect.py
src/cellfinder_core/detect/filters/plane/__init__.py
src/cellfinder_core/detect/filters/plane/multiprocessing.py
src/cellfinder_core/detect/filters/plane/plane_filter.py
src/cellfinder_core/detect/filters/volume/multiprocessing.py
src/cellfinder_core/detect/filters/volume/volume_filter.py

This PR hugely simplifies how multiprocessing is done during detection. Instead of manually handling individual `Process`es, a `Pool()` of available threads is created, and the 2D detection jobs asyncronously submitted to that worker pool. After submitting all those jobs, the 3D cell detection runs in the main thread, waiting for the outputs of the 2D analysis in order.
This significantly reduces the overhead of process management. Running cellfinder using the test data included goes from ~30s to ~2s for me locally. This speedup will be less dramatic on larger datasets, but not insignificant. On a ~10GB dataset the speedup is from ~2m05s to ~1m50s for me locally. The CI now runs noticably faster too, from ~15min before to ~10min now.
Reducing the code complexity also removes places where …

Improve Process handling during detection

---

.github/workflows/test_and_deploy.yml
CHANGELOG.md
tox.ini

As per https://github.com/brainglobe/bg-gitbook/pull/5, this drops Python 3.7 support. This only removes support for testing. For package wheel building I intend to drop the support in https://github.com/brainglobe/cellfinder-core/pull/41.

Drop Python 3.7 support

---

.github/workflows/test_and_deploy.yml
pyproject.toml

This reduces the amount of custom GH actions script needed to build & upload wheels.

Use cibuildwheel to build wheels

---

.github/workflows/test_and_deploy.yml

It seems unnessesary to test wheel/sdist building on every PR, and this testing will still be done when releaseing a release candidate to check it works before doing a full release.

Only test wheel building on tags

---

.gitignore
benchmarks/README.md
benchmarks/detect_and_classify.py
src/cellfinder_core/detect/detect.py
src/cellfinder_core/detect/filters/plane/plane_filter.py
src/cellfinder_core/detect/filters/volume/volume_filter.py

This fixes https://github.com/brainglobe/cellfinder-core/issues/52 - the issue there was that all planes were being read into memory before the 2D processing start, instead of being read into memory when they were being processed. This PR fixes that by storing the planes in a `Queue`, and removing them from that `Queue` when the 3D filtering is done.

Don't read all planes into memory at once

---

.github/workflows/test_and_deploy.yml
README.md
src/cellfinder_core/main.py
src/cellfinder_core/tools/prep.py
src/cellfinder_core/train/train_yml.py

This partially reverts https://github.com/brainglobe/cellfinder-core/pull/56, which changed the order of arguments and therefore broke `cellfinder`.

Revert changes to prep function arguments

---

src/cellfinder_core/__init__.py
src/cellfinder_core/classify/classify.py
src/cellfinder_core/classify/tools.py
src/cellfinder_core/detect/filters/volume/structure_splitting.py
src/cellfinder_core/detect/filters/volume/volume_filter.py
src/cellfinder_core/download/models.py
src/cellfinder_core/main.py
src/cellfinder_core/tools/prep.py
src/cellfinder_core/tools/tf.py
src/cellfinder_core/train/train_yml.py

This adds a logger that is specific to `cellfinder_core`, instead of using the root Python logger. This allows one to customize the `cellfinder-core` logger independently of other log messages, e.g. to show DEBUG messages just from cellfinder-core but not other packages:
```python
import logging
from cellfinder_core import logger
setLevel(logging.DEBUG)
```

Add cellfinder_core specific logger

---

src/cellfinder_core/detect/detect.py
src/cellfinder_core/tools/tools.py
tests/tests/test_integration/test_detection.py
tests/tests/test_unit/test_tools/test_tools_general.py

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).
This
- Updates `get_max_value` to use more robust code (calling a numpy function) instead of parsing the data type string
- Raises an error early if the data type of the image isn't integer
Fixes https://github.com/brainglobe/cellfinder-core/issues/67
I've added a new test for the new error.
No
If any features have changed, or have been added. Please explain how the documentation has been updated (and link to the associated PR). See [here](https://docs.cellfinder.info/for-developers/documentation) for details.

Error early if image data isn't integer datatype

---

src/cellfinder_core/detect/detect.py

For some reason https://github.com/brainglobe/cellfinder-core/pull/68 works on the local tests here in `cellfinder-core`, but when I was trying to run something in `cellfinder-napari` the datatype detection was raising an error. This PR fixes that error.

Fix datatype detection

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg
src/cellfinder_core/classify/augment.py
src/cellfinder_core/classify/resnet.py
src/cellfinder_core/classify/tools.py
src/cellfinder_core/detect/filters/setup_filters.py
src/cellfinder_core/train/train_yml.py
tests/tests/test_integration/test_detection.py
tests/tests/test_unit/test_tools/test_geometry.py

This applies the standard pre-commit-config.yaml file from https://github.com/SainsburyWellcomeCentre/python-cookiecutter, and fixes files as needed for this new config.

Use standard pre-commit config

---

src/cellfinder_core/detect/filters/volume/volume_filter.py

This loop already has a `tqdm` progress bar, so the print statement is redundant and interrupts the progress bar.

Remove print statment from 3D filter

---

benchmarks/detect_and_classify.py

It turns out if you increase the size of a dask array using `da.repeat(...)`, dask is clever and doesn't make actual copies of the data. This is great, unless you're running memory benchmarks and *want* the memory useage to increase 🙈 
This PR changes the sample data to be random data generated by dask, instead of repeating existing data. Although the cell detection results won't be meaningful on this data, it provides a easy way to run memory benchmarks.
To confirm this works, here's the memory usage of just detection, which shows a clear increase when the array size is increased:

Use random arrays for memory testing

---

src/cellfinder_core/tools/source_files.py

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).
We use `pkg_resources` which is deprecated (and therefore our tests fail).
Uses a relative path to config files instead of `pkg_resources.filename`.
- 
Tests were failing before due to the deprecation warning, and now pass.
No.
No.

avoid using deprecated pkg_resources

---

tests/tests/conftest.py
tests/tests/test_integration/test_detection.py

Adds a fixture that generates simple synthetic signal and background arrays
Background array is black, signal array has 8 slightly blurred bright spots.
The synthetic data is useful for testing.
See Description.
n/a
Added a test that checks cell detection finds 8 cells in the programmatically generated synthetic data, as expected.
No.

Fixture for programmatic creation of synthetic data

---

pyproject.toml

Tested on the run at https://github.com/brainglobe/cellfinder-core/actions/runs/4103823424/jobs/7078512416, which passed.
Fixes https://github.com/brainglobe/cellfinder-core/issues/51.

Add macOS arm64 wheel building

---

.github/workflows/test_and_deploy.yml

Fixes https://github.com/brainglobe/cellfinder-core/issues/72. The previous code used the `pull_request` event to get the SHA. The new version is more generic, using provided environment variables to get the checkout url.

Allow cellfinder tests to run on branches

---

src/cellfinder_core/detect/filters/plane/base_tile_filter.py
src/cellfinder_core/detect/filters/plane/tile_walker.py

In my 3D filtering branch, `is_low_average` was causing issues with `numba` not being able to compile it using nopython mode. This PR fixes that, and greatly simplifies `is_low_average`.

Simplify implemention of is_low_average

---

pyproject.toml

See https://github.com/brainglobe/cellfinder-core/issues/103 - tests are failing with the new version of tensorflow, so until we've sorted it probably easiest to pin the tensorflow version.

Pin tensorflow to < 2.12.0

---

pyproject.toml
tox.ini

Fixes https://github.com/brainglobe/cellfinder-core/issues/86. Since the coverage config was already listed in `pyproject.toml`, I migrated it to there from `tox.ini` and fixed it.

Fix test coverage data collection

---

MANIFEST.in

Fixes https://github.com/brainglobe/cellfinder-core/issues/96. As intended, this speeds up building the distribution. The entries are redundant now we're not using Cython, and setuptools_scm will make sure that the file in cellfinder_core/config is included in the distribution.

Remove manifest file

---

src/cellfinder_core/detect/filters/volume/structure_detection.py

As discussed in https://github.com/brainglobe/cellfinder-core/issues/111, it was decided to remove this. Fixes https://github.com/brainglobe/cellfinder-core/issues/111.

Remove connect_eight()

---

src/cellfinder_core/detect/filters/volume/structure_detection.py

Fixes https://github.com/brainglobe/cellfinder-core/issues/109 - there doesn't seem to be any code marked as test in `structure_detection.py` now.
`get_structure_centre_wrapper` is used in the code, so I've:
- Typed it
- Added a short docstring
- Removed un-used code for Dict input

Clean up structure_centre_wrapper

---

src/cellfinder_core/detect/filters/volume/ball_filter.py

This finishes typing on `BallFilter`. Because the filter doesn't work when some of the initial arguments are `None`, I've just removed all the default arguments to keep it simple.

Type ball filter

---

src/cellfinder_core/detect/detect.py
tests/tests/test_integration/test_detection.py

Adds a bit more test coverage. Also updates the error type from `IOError` to `ValueError`, as the error is being raised because of an issue with a value passed to a function, not an issue with input/output.

Test for error when data dimensionality is wrong

---

.codecov.yml
.github/workflows/test_and_deploy.yml
.github/workflows/test_numba_off.yml
tox.ini

Fixes https://github.com/brainglobe/cellfinder-core/issues/110. This adds a new CI workflow that only runs on `main` that disables numba, and therefore collects code coverage for the parts of the code that would otherwise be optimised by numba. The tests are slow (~20 mins), but not unreasonably slow, so running them only on commits to `main` seems like a good compromise.
I've also enabled carryforward flags for these parts of the code in codecov. This will automatically carry forward the covered lines on main to pull requests, so coverage isn't going up and down in `main` compared to pull requests where the new workflow isn't run.

Collect coverage of numba decorated code

---

benchmarks/filter_3d.py
src/cellfinder_core/detect/filters/plane/plane_filter.py
src/cellfinder_core/detect/filters/volume/ball_filter.py
src/cellfinder_core/detect/filters/volume/structure_splitting.py

I see no reason why this mask can't be bool, and all tests seem to pass. This should save a little bit of memory.
This is the first of a few PRs I'm going to open to reduce memory usage. Fixes https://github.com/brainglobe/cellfinder-core/issues/128

Use bool dtype for good tiles mask

---

.github/workflows/test_and_deploy.yml
MANIFEST.in

Fixes https://github.com/brainglobe/cellfinder-core/issues/144.
It turns out that https://github.com/brainglobe/cellfinder-core/pull/126 was a mistake 🙈 , and a `MANIFEST.in` file is needed to strip out the test data from the soure distribution.

Remove cibuildwheel and build pure-Python wheel

---

src/cellfinder_core/detect/filters/volume/structure_detection.py
src/cellfinder_core/detect/filters/volume/structure_splitting.py
src/cellfinder_core/detect/filters/volume/volume_filter.py
tests/tests/test_unit/test_detect/test_filters/test_volume_filters/test_structure_detection.py

I think this simplifies the code a bit, and also reduces the memory footprint slightly by not taking a copy of the planes and casting them to `uint64`.
Fixes https://github.com/brainglobe/cellfinder-core/issues/100.

Don't cast planes to uint64 in structure detection

---

pyproject.toml
src/cellfinder_core/detect/detect.py
src/cellfinder_core/detect/filters/plane/classical_filter.py
src/cellfinder_core/detect/filters/plane/plane_filter.py
src/cellfinder_core/detect/filters/plane/tile_walker.py
src/cellfinder_core/detect/filters/volume/ball_filter.py
src/cellfinder_core/detect/filters/volume/structure_detection.py
src/cellfinder_core/detect/filters/volume/structure_splitting.py
src/cellfinder_core/detect/filters/volume/volume_filter.py

I thought this might be a good first step in tackling https://github.com/brainglobe/cellfinder-core/issues/158. It doesn't look like it helped or revealed any errors in the code itself, but seems like a good idea to finish typing the whole of the `cellfinder_core.detect`, and enforce it going forward.

Force typing in detect sub-module

---

.pre-commit-config.yaml
benchmarks/filter_3d.py
src/cellfinder_core/detect/detect.py
src/cellfinder_core/detect/filters/plane/plane_filter.py
src/cellfinder_core/detect/filters/volume/ball_filter.py
src/cellfinder_core/detect/filters/volume/structure_detection.py
src/cellfinder_core/detect/filters/volume/volume_filter.py
src/cellfinder_core/tools/array_operations.py
src/cellfinder_core/tools/geometry.py

Adding numpy, numba, and dask to the environment in which type checking is done revealed some more fixes that needed making. Builds on top of https://github.com/brainglobe/cellfinder-core/pull/161

Add numpy to typing deps

---

src/cellfinder_core/__init__.py

`cellfinder_core.__version__` is statically set at `0.3.1` but we're now at (at least) `0.4.0`.
There are also some underlying problems with building on conda because of this; for example needing to fix the cellfinder-core to version `0.3.1` in the conda-forge recipe for the brainglobe meta-package. (https://github.com/conda-forge/staged-recipes/pull/23136)
`cellfinder_core.__version__` will now read from the metadata in pyproject.toml. There shouldn't be a need to manually update the version number in future releases.
Local pip install of the package now returns the dynamic version when requested.
Not a breaking change, but we need a new version uploaded because `v0.4.0` still reports that it's version `0.3.1` when …

Fix dynamic versioning

---

.pre-commit-config.yaml
pyproject.toml

- Configuration file needs to be specified to get mypy to correctly run checks
- Don't bother installing numba in pre-commit environment, as it doesn't provide any types yet
- Ignore missing imports for modules without typing

Fix mypy type checking

---

README.md
src/cellfinder_core/__init__.py

See https://github.com/brainglobe/BrainGlobe/issues/27 - this PR is for `conda-forge` compatibility reasons.
This PR forbids the import of `cellfinder_core` when `tensorflow` is not installed.
Note that we do not need to remove `tensorflow` from the `pyproject.toml` dependencies - these are read only by `pip` and not by `conda`.
[Resolves step 1 of this issue.](https://github.com/brainglobe/BrainGlobe/issues/27)
Local testing of `pip` package install:
```sh
$ conda activate cellfinder
(cellfinder) $ pip install .
(cellfinder) $ python 
>> import cellfinder_core
>> exit()
(cellfinder) $ pip uninstall tensorflow
(cellfinder) $ python
>> import cellfinder_core
(cellfinder) $ pip install tensorflow
(cellfinder) $ python …
```

Forbid import when `tensorflow` is not installed

---

README.md

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).
- https://github.com/conda-forge/cellfinder-core-feedstock/issues/13
- #186
This is an update to README.md to reflect `conda` install compatibility currently under discussion [on the feedstock](https://github.com/conda-forge/cellfinder-core-feedstock/issues/13), and the changes in #186.

Update README in light of possible noarch build

---

.github/workflows/test_and_deploy.yml
MANIFEST.in

We currently ship the `benchmarks` and `tests` with the source distribution. We shouldn't do this.
- Tells the `MANIFEST.in` to ignore the unnecessary directories.
- Adds a MANIFEST check to the CI, to bring it in line with other BrainGlobe packages.
- Closes #193 
- CI tests pass : [THERE WAS A BUG IN TOX-GH-ACTIONS](https://github.com/ymyzk/tox-gh-actions/pull/183)
- Manual `python -m build` followed by inspection of the source `tar.gz` confirm source contents are as expected.
No
No

MANIFEST only necessary files for package install

---

.github/workflows/test_include_guard.yaml

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).
Tests the include-guard that denies use of the tools when `tensorflow` is not available.
Adds a short check to make sure that the `tensorflow` include guard is behaving itself on `ubuntu` and `macOS`.
- `pip install -e .` should successfully fetch `tensorflow` and allow import.
- If `tensorflow` is not installed, importing the module should fail. Conditions for this test are achieved by having pip uninstall `tensorflow`.
- Closes #203 
Locally running the commands produces the outcomes that are checked against.
New workflow has been introduced to check the results are as …

CI Check against `tensorflow` include guard
